language: go
go:
  - "1.12"
  - tip
services:
  - redis-server
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
